spring:
  thymeleaf:
    prefix:  /templates/,/static/ueditor/
    suffix: .html
    cache: false
  mvc:
    view:
      prefix: /WEB-INF/views/,/static/ueditor/
      suffix: .jsp,.html
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gd_base
    data-username: gd_base
    data-password: 11
    driver-class-name: com.mysql.jdbc.Driver
  #redis:
   # host: 127.0.0.1
    #password: minstone123456
    #port: 6379
    #pool:
     # max-idle: 100
      #min-idle: 1
      #max-active: 1000
      #max-wait: -1
    #timeout: 20000
  #rabbitmq:
   # host: 127.0.0.1
    #port: 5672
    #virtual-host: testhost
    #username: admin
    #password: abc123
#mybatis:
 # mapper-locations: classpath:mapper/*.xml
