package com.lwt.springboot.domain;

import java.util.Date;

public class OuternetUserBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.U_ID
     *
     * @mbggenerated
     */
    private String uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.U_TYPE
     *
     * @mbggenerated
     */
    private String uType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.U_NAME
     *
     * @mbggenerated
     */
    private String uName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.U_PWD
     *
     * @mbggenerated
     */
    private String uPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.LICENSE
     *
     * @mbggenerated
     */
    private String license;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.ORG_CODE
     *
     * @mbggenerated
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.CORPORATION
     *
     * @mbggenerated
     */
    private String corporation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.CORPORATION_ID
     *
     * @mbggenerated
     */
    private String corporationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.E_MAIL
     *
     * @mbggenerated
     */
    private String eMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.MOBILE_PHONE
     *
     * @mbggenerated
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.TEL_PHONE
     *
     * @mbggenerated
     */
    private String telPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.ADDRESS
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.PWD_QUESTION
     *
     * @mbggenerated
     */
    private String pwdQuestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.PWD_ANSWER
     *
     * @mbggenerated
     */
    private String pwdAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.PAPER_TYPE
     *
     * @mbggenerated
     */
    private String paperType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.PAPER_CODE
     *
     * @mbggenerated
     */
    private String paperCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.UNIT_CODE
     *
     * @mbggenerated
     */
    private String unitCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.CHECK_STATE
     *
     * @mbggenerated
     */
    private String checkState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.CA_SN
     *
     * @mbggenerated
     */
    private String caSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.BAR_CODE
     *
     * @mbggenerated
     */
    private String barCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.LOCKDATE
     *
     * @mbggenerated
     */
    private Date lockdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.U_TYPE2
     *
     * @mbggenerated
     */
    private String uType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.IS_NEW_ESTABLISH
     *
     * @mbggenerated
     */
    private String isNewEstablish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.USER_REG_TIME
     *
     * @mbggenerated
     */
    private Date userRegTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.HANDLER_NAME
     *
     * @mbggenerated
     */
    private String handlerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.HANDLER_ID
     *
     * @mbggenerated
     */
    private String handlerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.E_UID
     *
     * @mbggenerated
     */
    private String eUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.EXCHANGE_STATUS
     *
     * @mbggenerated
     */
    private Short exchangeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.PWD_TYPE
     *
     * @mbggenerated
     */
    private Short pwdType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.IP_NUMBER
     *
     * @mbggenerated
     */
    private String ipNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.VERSION
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_USER.IS_SUPPLY
     *
     * @mbggenerated
     */
    private Short isSupply;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    public OuternetUserBean(String uId, String uType, String uName, String uPwd, String type, String name, String license, String orgCode, String corporation, String corporationId, String eMail, String mobilePhone, String telPhone, String code, String address, String pwdQuestion, String pwdAnswer, String paperType, String paperCode, String unitCode, String checkState, String caSn, String barCode, Date lockdate, String uType2, String isNewEstablish, Date userRegTime, String handlerName, String handlerId, String eUid, Short exchangeStatus, Short pwdType, String ipNumber, String version, Short isSupply) {
        this.uId = uId;
        this.uType = uType;
        this.uName = uName;
        this.uPwd = uPwd;
        this.type = type;
        this.name = name;
        this.license = license;
        this.orgCode = orgCode;
        this.corporation = corporation;
        this.corporationId = corporationId;
        this.eMail = eMail;
        this.mobilePhone = mobilePhone;
        this.telPhone = telPhone;
        this.code = code;
        this.address = address;
        this.pwdQuestion = pwdQuestion;
        this.pwdAnswer = pwdAnswer;
        this.paperType = paperType;
        this.paperCode = paperCode;
        this.unitCode = unitCode;
        this.checkState = checkState;
        this.caSn = caSn;
        this.barCode = barCode;
        this.lockdate = lockdate;
        this.uType2 = uType2;
        this.isNewEstablish = isNewEstablish;
        this.userRegTime = userRegTime;
        this.handlerName = handlerName;
        this.handlerId = handlerId;
        this.eUid = eUid;
        this.exchangeStatus = exchangeStatus;
        this.pwdType = pwdType;
        this.ipNumber = ipNumber;
        this.version = version;
        this.isSupply = isSupply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.U_ID
     *
     * @return the value of OUTERNET_USER.U_ID
     *
     * @mbggenerated
     */
    public String getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.U_TYPE
     *
     * @return the value of OUTERNET_USER.U_TYPE
     *
     * @mbggenerated
     */
    public String getuType() {
        return uType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.U_NAME
     *
     * @return the value of OUTERNET_USER.U_NAME
     *
     * @mbggenerated
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.U_PWD
     *
     * @return the value of OUTERNET_USER.U_PWD
     *
     * @mbggenerated
     */
    public String getuPwd() {
        return uPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.TYPE
     *
     * @return the value of OUTERNET_USER.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.NAME
     *
     * @return the value of OUTERNET_USER.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.LICENSE
     *
     * @return the value of OUTERNET_USER.LICENSE
     *
     * @mbggenerated
     */
    public String getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.ORG_CODE
     *
     * @return the value of OUTERNET_USER.ORG_CODE
     *
     * @mbggenerated
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.CORPORATION
     *
     * @return the value of OUTERNET_USER.CORPORATION
     *
     * @mbggenerated
     */
    public String getCorporation() {
        return corporation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.CORPORATION_ID
     *
     * @return the value of OUTERNET_USER.CORPORATION_ID
     *
     * @mbggenerated
     */
    public String getCorporationId() {
        return corporationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.E_MAIL
     *
     * @return the value of OUTERNET_USER.E_MAIL
     *
     * @mbggenerated
     */
    public String geteMail() {
        return eMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.MOBILE_PHONE
     *
     * @return the value of OUTERNET_USER.MOBILE_PHONE
     *
     * @mbggenerated
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.TEL_PHONE
     *
     * @return the value of OUTERNET_USER.TEL_PHONE
     *
     * @mbggenerated
     */
    public String getTelPhone() {
        return telPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.CODE
     *
     * @return the value of OUTERNET_USER.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.ADDRESS
     *
     * @return the value of OUTERNET_USER.ADDRESS
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.PWD_QUESTION
     *
     * @return the value of OUTERNET_USER.PWD_QUESTION
     *
     * @mbggenerated
     */
    public String getPwdQuestion() {
        return pwdQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.PWD_ANSWER
     *
     * @return the value of OUTERNET_USER.PWD_ANSWER
     *
     * @mbggenerated
     */
    public String getPwdAnswer() {
        return pwdAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.PAPER_TYPE
     *
     * @return the value of OUTERNET_USER.PAPER_TYPE
     *
     * @mbggenerated
     */
    public String getPaperType() {
        return paperType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.PAPER_CODE
     *
     * @return the value of OUTERNET_USER.PAPER_CODE
     *
     * @mbggenerated
     */
    public String getPaperCode() {
        return paperCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.UNIT_CODE
     *
     * @return the value of OUTERNET_USER.UNIT_CODE
     *
     * @mbggenerated
     */
    public String getUnitCode() {
        return unitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.CHECK_STATE
     *
     * @return the value of OUTERNET_USER.CHECK_STATE
     *
     * @mbggenerated
     */
    public String getCheckState() {
        return checkState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.CA_SN
     *
     * @return the value of OUTERNET_USER.CA_SN
     *
     * @mbggenerated
     */
    public String getCaSn() {
        return caSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.BAR_CODE
     *
     * @return the value of OUTERNET_USER.BAR_CODE
     *
     * @mbggenerated
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.LOCKDATE
     *
     * @return the value of OUTERNET_USER.LOCKDATE
     *
     * @mbggenerated
     */
    public Date getLockdate() {
        return lockdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.U_TYPE2
     *
     * @return the value of OUTERNET_USER.U_TYPE2
     *
     * @mbggenerated
     */
    public String getuType2() {
        return uType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.IS_NEW_ESTABLISH
     *
     * @return the value of OUTERNET_USER.IS_NEW_ESTABLISH
     *
     * @mbggenerated
     */
    public String getIsNewEstablish() {
        return isNewEstablish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.USER_REG_TIME
     *
     * @return the value of OUTERNET_USER.USER_REG_TIME
     *
     * @mbggenerated
     */
    public Date getUserRegTime() {
        return userRegTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.HANDLER_NAME
     *
     * @return the value of OUTERNET_USER.HANDLER_NAME
     *
     * @mbggenerated
     */
    public String getHandlerName() {
        return handlerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.HANDLER_ID
     *
     * @return the value of OUTERNET_USER.HANDLER_ID
     *
     * @mbggenerated
     */
    public String getHandlerId() {
        return handlerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.E_UID
     *
     * @return the value of OUTERNET_USER.E_UID
     *
     * @mbggenerated
     */
    public String geteUid() {
        return eUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.EXCHANGE_STATUS
     *
     * @return the value of OUTERNET_USER.EXCHANGE_STATUS
     *
     * @mbggenerated
     */
    public Short getExchangeStatus() {
        return exchangeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.PWD_TYPE
     *
     * @return the value of OUTERNET_USER.PWD_TYPE
     *
     * @mbggenerated
     */
    public Short getPwdType() {
        return pwdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.IP_NUMBER
     *
     * @return the value of OUTERNET_USER.IP_NUMBER
     *
     * @mbggenerated
     */
    public String getIpNumber() {
        return ipNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.VERSION
     *
     * @return the value of OUTERNET_USER.VERSION
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_USER.IS_SUPPLY
     *
     * @return the value of OUTERNET_USER.IS_SUPPLY
     *
     * @mbggenerated
     */
    public Short getIsSupply() {
        return isSupply;
    }
}