package com.lwt.springboot.domain;

import java.util.Date;

public class outernetBundlingUserBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_BUNDLING_USER.BUNDLING_ID
     *
     * @mbggenerated
     */
    private String bundlingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_BUNDLING_USER.LOGIN_ID
     *
     * @mbggenerated
     */
    private String loginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_BUNDLING_USER.USER_CODE
     *
     * @mbggenerated
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_BUNDLING_USER.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_BUNDLING_USER.IS_VALID
     *
     * @mbggenerated
     */
    private Short isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_BUNDLING_USER.ISP_NAME
     *
     * @mbggenerated
     */
    private String ispName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_BUNDLING_USER.ISP_CODE
     *
     * @mbggenerated
     */
    private String ispCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_BUNDLING_USER.LOCAL_USER
     *
     * @mbggenerated
     */
    private String localUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_BUNDLING_USER.BUNDLING_USERID_CODE
     *
     * @mbggenerated
     */
    private String bundlingUseridCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_BUNDLING_USER.BUNDLING_IS_REAL
     *
     * @mbggenerated
     */
    private String bundlingIsReal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OUTERNET_BUNDLING_USER.BUNDLING_UPDATE_TIME
     *
     * @mbggenerated
     */
    private String bundlingUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_BUNDLING_USER
     *
     * @mbggenerated
     */
    public outernetBundlingUserBean(String bundlingId, String loginId, String userCode, Date createDate, Short isValid, String ispName, String ispCode, String localUser, String bundlingUseridCode, String bundlingIsReal, String bundlingUpdateTime) {
        this.bundlingId = bundlingId;
        this.loginId = loginId;
        this.userCode = userCode;
        this.createDate = createDate;
        this.isValid = isValid;
        this.ispName = ispName;
        this.ispCode = ispCode;
        this.localUser = localUser;
        this.bundlingUseridCode = bundlingUseridCode;
        this.bundlingIsReal = bundlingIsReal;
        this.bundlingUpdateTime = bundlingUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_BUNDLING_USER.BUNDLING_ID
     *
     * @return the value of OUTERNET_BUNDLING_USER.BUNDLING_ID
     *
     * @mbggenerated
     */
    public String getBundlingId() {
        return bundlingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_BUNDLING_USER.LOGIN_ID
     *
     * @return the value of OUTERNET_BUNDLING_USER.LOGIN_ID
     *
     * @mbggenerated
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_BUNDLING_USER.USER_CODE
     *
     * @return the value of OUTERNET_BUNDLING_USER.USER_CODE
     *
     * @mbggenerated
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_BUNDLING_USER.CREATE_DATE
     *
     * @return the value of OUTERNET_BUNDLING_USER.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_BUNDLING_USER.IS_VALID
     *
     * @return the value of OUTERNET_BUNDLING_USER.IS_VALID
     *
     * @mbggenerated
     */
    public Short getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_BUNDLING_USER.ISP_NAME
     *
     * @return the value of OUTERNET_BUNDLING_USER.ISP_NAME
     *
     * @mbggenerated
     */
    public String getIspName() {
        return ispName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_BUNDLING_USER.ISP_CODE
     *
     * @return the value of OUTERNET_BUNDLING_USER.ISP_CODE
     *
     * @mbggenerated
     */
    public String getIspCode() {
        return ispCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_BUNDLING_USER.LOCAL_USER
     *
     * @return the value of OUTERNET_BUNDLING_USER.LOCAL_USER
     *
     * @mbggenerated
     */
    public String getLocalUser() {
        return localUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_BUNDLING_USER.BUNDLING_USERID_CODE
     *
     * @return the value of OUTERNET_BUNDLING_USER.BUNDLING_USERID_CODE
     *
     * @mbggenerated
     */
    public String getBundlingUseridCode() {
        return bundlingUseridCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_BUNDLING_USER.BUNDLING_IS_REAL
     *
     * @return the value of OUTERNET_BUNDLING_USER.BUNDLING_IS_REAL
     *
     * @mbggenerated
     */
    public String getBundlingIsReal() {
        return bundlingIsReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OUTERNET_BUNDLING_USER.BUNDLING_UPDATE_TIME
     *
     * @return the value of OUTERNET_BUNDLING_USER.BUNDLING_UPDATE_TIME
     *
     * @mbggenerated
     */
    public String getBundlingUpdateTime() {
        return bundlingUpdateTime;
    }
}