package com.lwt.springboot.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class OuternetUserBeanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    public OuternetUserBeanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andUIdIsNull() {
            addCriterion("U_ID is null");
            return (Criteria) this;
        }

        public Criteria andUIdIsNotNull() {
            addCriterion("U_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUIdEqualTo(String value) {
            addCriterion("U_ID =", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotEqualTo(String value) {
            addCriterion("U_ID <>", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdGreaterThan(String value) {
            addCriterion("U_ID >", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdGreaterThanOrEqualTo(String value) {
            addCriterion("U_ID >=", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdLessThan(String value) {
            addCriterion("U_ID <", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdLessThanOrEqualTo(String value) {
            addCriterion("U_ID <=", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdLike(String value) {
            addCriterion("U_ID like", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotLike(String value) {
            addCriterion("U_ID not like", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdIn(List<String> values) {
            addCriterion("U_ID in", values, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotIn(List<String> values) {
            addCriterion("U_ID not in", values, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdBetween(String value1, String value2) {
            addCriterion("U_ID between", value1, value2, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotBetween(String value1, String value2) {
            addCriterion("U_ID not between", value1, value2, "uId");
            return (Criteria) this;
        }

        public Criteria andUTypeIsNull() {
            addCriterion("U_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andUTypeIsNotNull() {
            addCriterion("U_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andUTypeEqualTo(String value) {
            addCriterion("U_TYPE =", value, "uType");
            return (Criteria) this;
        }

        public Criteria andUTypeNotEqualTo(String value) {
            addCriterion("U_TYPE <>", value, "uType");
            return (Criteria) this;
        }

        public Criteria andUTypeGreaterThan(String value) {
            addCriterion("U_TYPE >", value, "uType");
            return (Criteria) this;
        }

        public Criteria andUTypeGreaterThanOrEqualTo(String value) {
            addCriterion("U_TYPE >=", value, "uType");
            return (Criteria) this;
        }

        public Criteria andUTypeLessThan(String value) {
            addCriterion("U_TYPE <", value, "uType");
            return (Criteria) this;
        }

        public Criteria andUTypeLessThanOrEqualTo(String value) {
            addCriterion("U_TYPE <=", value, "uType");
            return (Criteria) this;
        }

        public Criteria andUTypeLike(String value) {
            addCriterion("U_TYPE like", value, "uType");
            return (Criteria) this;
        }

        public Criteria andUTypeNotLike(String value) {
            addCriterion("U_TYPE not like", value, "uType");
            return (Criteria) this;
        }

        public Criteria andUTypeIn(List<String> values) {
            addCriterion("U_TYPE in", values, "uType");
            return (Criteria) this;
        }

        public Criteria andUTypeNotIn(List<String> values) {
            addCriterion("U_TYPE not in", values, "uType");
            return (Criteria) this;
        }

        public Criteria andUTypeBetween(String value1, String value2) {
            addCriterion("U_TYPE between", value1, value2, "uType");
            return (Criteria) this;
        }

        public Criteria andUTypeNotBetween(String value1, String value2) {
            addCriterion("U_TYPE not between", value1, value2, "uType");
            return (Criteria) this;
        }

        public Criteria andUNameIsNull() {
            addCriterion("U_NAME is null");
            return (Criteria) this;
        }

        public Criteria andUNameIsNotNull() {
            addCriterion("U_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andUNameEqualTo(String value) {
            addCriterion("U_NAME =", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameNotEqualTo(String value) {
            addCriterion("U_NAME <>", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameGreaterThan(String value) {
            addCriterion("U_NAME >", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameGreaterThanOrEqualTo(String value) {
            addCriterion("U_NAME >=", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameLessThan(String value) {
            addCriterion("U_NAME <", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameLessThanOrEqualTo(String value) {
            addCriterion("U_NAME <=", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameLike(String value) {
            addCriterion("U_NAME like", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameNotLike(String value) {
            addCriterion("U_NAME not like", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameIn(List<String> values) {
            addCriterion("U_NAME in", values, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameNotIn(List<String> values) {
            addCriterion("U_NAME not in", values, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameBetween(String value1, String value2) {
            addCriterion("U_NAME between", value1, value2, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameNotBetween(String value1, String value2) {
            addCriterion("U_NAME not between", value1, value2, "uName");
            return (Criteria) this;
        }

        public Criteria andUPwdIsNull() {
            addCriterion("U_PWD is null");
            return (Criteria) this;
        }

        public Criteria andUPwdIsNotNull() {
            addCriterion("U_PWD is not null");
            return (Criteria) this;
        }

        public Criteria andUPwdEqualTo(String value) {
            addCriterion("U_PWD =", value, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdNotEqualTo(String value) {
            addCriterion("U_PWD <>", value, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdGreaterThan(String value) {
            addCriterion("U_PWD >", value, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdGreaterThanOrEqualTo(String value) {
            addCriterion("U_PWD >=", value, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdLessThan(String value) {
            addCriterion("U_PWD <", value, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdLessThanOrEqualTo(String value) {
            addCriterion("U_PWD <=", value, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdLike(String value) {
            addCriterion("U_PWD like", value, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdNotLike(String value) {
            addCriterion("U_PWD not like", value, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdIn(List<String> values) {
            addCriterion("U_PWD in", values, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdNotIn(List<String> values) {
            addCriterion("U_PWD not in", values, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdBetween(String value1, String value2) {
            addCriterion("U_PWD between", value1, value2, "uPwd");
            return (Criteria) this;
        }

        public Criteria andUPwdNotBetween(String value1, String value2) {
            addCriterion("U_PWD not between", value1, value2, "uPwd");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("TYPE =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("TYPE <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("TYPE >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TYPE >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("TYPE <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("TYPE <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("TYPE like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("TYPE not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("TYPE in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("TYPE not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("TYPE between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("TYPE not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andLicenseIsNull() {
            addCriterion("LICENSE is null");
            return (Criteria) this;
        }

        public Criteria andLicenseIsNotNull() {
            addCriterion("LICENSE is not null");
            return (Criteria) this;
        }

        public Criteria andLicenseEqualTo(String value) {
            addCriterion("LICENSE =", value, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseNotEqualTo(String value) {
            addCriterion("LICENSE <>", value, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseGreaterThan(String value) {
            addCriterion("LICENSE >", value, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseGreaterThanOrEqualTo(String value) {
            addCriterion("LICENSE >=", value, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseLessThan(String value) {
            addCriterion("LICENSE <", value, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseLessThanOrEqualTo(String value) {
            addCriterion("LICENSE <=", value, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseLike(String value) {
            addCriterion("LICENSE like", value, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseNotLike(String value) {
            addCriterion("LICENSE not like", value, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseIn(List<String> values) {
            addCriterion("LICENSE in", values, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseNotIn(List<String> values) {
            addCriterion("LICENSE not in", values, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseBetween(String value1, String value2) {
            addCriterion("LICENSE between", value1, value2, "license");
            return (Criteria) this;
        }

        public Criteria andLicenseNotBetween(String value1, String value2) {
            addCriterion("LICENSE not between", value1, value2, "license");
            return (Criteria) this;
        }

        public Criteria andOrgCodeIsNull() {
            addCriterion("ORG_CODE is null");
            return (Criteria) this;
        }

        public Criteria andOrgCodeIsNotNull() {
            addCriterion("ORG_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andOrgCodeEqualTo(String value) {
            addCriterion("ORG_CODE =", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotEqualTo(String value) {
            addCriterion("ORG_CODE <>", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeGreaterThan(String value) {
            addCriterion("ORG_CODE >", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_CODE >=", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeLessThan(String value) {
            addCriterion("ORG_CODE <", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeLessThanOrEqualTo(String value) {
            addCriterion("ORG_CODE <=", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeLike(String value) {
            addCriterion("ORG_CODE like", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotLike(String value) {
            addCriterion("ORG_CODE not like", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeIn(List<String> values) {
            addCriterion("ORG_CODE in", values, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotIn(List<String> values) {
            addCriterion("ORG_CODE not in", values, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeBetween(String value1, String value2) {
            addCriterion("ORG_CODE between", value1, value2, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotBetween(String value1, String value2) {
            addCriterion("ORG_CODE not between", value1, value2, "orgCode");
            return (Criteria) this;
        }

        public Criteria andCorporationIsNull() {
            addCriterion("CORPORATION is null");
            return (Criteria) this;
        }

        public Criteria andCorporationIsNotNull() {
            addCriterion("CORPORATION is not null");
            return (Criteria) this;
        }

        public Criteria andCorporationEqualTo(String value) {
            addCriterion("CORPORATION =", value, "corporation");
            return (Criteria) this;
        }

        public Criteria andCorporationNotEqualTo(String value) {
            addCriterion("CORPORATION <>", value, "corporation");
            return (Criteria) this;
        }

        public Criteria andCorporationGreaterThan(String value) {
            addCriterion("CORPORATION >", value, "corporation");
            return (Criteria) this;
        }

        public Criteria andCorporationGreaterThanOrEqualTo(String value) {
            addCriterion("CORPORATION >=", value, "corporation");
            return (Criteria) this;
        }

        public Criteria andCorporationLessThan(String value) {
            addCriterion("CORPORATION <", value, "corporation");
            return (Criteria) this;
        }

        public Criteria andCorporationLessThanOrEqualTo(String value) {
            addCriterion("CORPORATION <=", value, "corporation");
            return (Criteria) this;
        }

        public Criteria andCorporationLike(String value) {
            addCriterion("CORPORATION like", value, "corporation");
            return (Criteria) this;
        }

        public Criteria andCorporationNotLike(String value) {
            addCriterion("CORPORATION not like", value, "corporation");
            return (Criteria) this;
        }

        public Criteria andCorporationIn(List<String> values) {
            addCriterion("CORPORATION in", values, "corporation");
            return (Criteria) this;
        }

        public Criteria andCorporationNotIn(List<String> values) {
            addCriterion("CORPORATION not in", values, "corporation");
            return (Criteria) this;
        }

        public Criteria andCorporationBetween(String value1, String value2) {
            addCriterion("CORPORATION between", value1, value2, "corporation");
            return (Criteria) this;
        }

        public Criteria andCorporationNotBetween(String value1, String value2) {
            addCriterion("CORPORATION not between", value1, value2, "corporation");
            return (Criteria) this;
        }

        public Criteria andCorporationIdIsNull() {
            addCriterion("CORPORATION_ID is null");
            return (Criteria) this;
        }

        public Criteria andCorporationIdIsNotNull() {
            addCriterion("CORPORATION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCorporationIdEqualTo(String value) {
            addCriterion("CORPORATION_ID =", value, "corporationId");
            return (Criteria) this;
        }

        public Criteria andCorporationIdNotEqualTo(String value) {
            addCriterion("CORPORATION_ID <>", value, "corporationId");
            return (Criteria) this;
        }

        public Criteria andCorporationIdGreaterThan(String value) {
            addCriterion("CORPORATION_ID >", value, "corporationId");
            return (Criteria) this;
        }

        public Criteria andCorporationIdGreaterThanOrEqualTo(String value) {
            addCriterion("CORPORATION_ID >=", value, "corporationId");
            return (Criteria) this;
        }

        public Criteria andCorporationIdLessThan(String value) {
            addCriterion("CORPORATION_ID <", value, "corporationId");
            return (Criteria) this;
        }

        public Criteria andCorporationIdLessThanOrEqualTo(String value) {
            addCriterion("CORPORATION_ID <=", value, "corporationId");
            return (Criteria) this;
        }

        public Criteria andCorporationIdLike(String value) {
            addCriterion("CORPORATION_ID like", value, "corporationId");
            return (Criteria) this;
        }

        public Criteria andCorporationIdNotLike(String value) {
            addCriterion("CORPORATION_ID not like", value, "corporationId");
            return (Criteria) this;
        }

        public Criteria andCorporationIdIn(List<String> values) {
            addCriterion("CORPORATION_ID in", values, "corporationId");
            return (Criteria) this;
        }

        public Criteria andCorporationIdNotIn(List<String> values) {
            addCriterion("CORPORATION_ID not in", values, "corporationId");
            return (Criteria) this;
        }

        public Criteria andCorporationIdBetween(String value1, String value2) {
            addCriterion("CORPORATION_ID between", value1, value2, "corporationId");
            return (Criteria) this;
        }

        public Criteria andCorporationIdNotBetween(String value1, String value2) {
            addCriterion("CORPORATION_ID not between", value1, value2, "corporationId");
            return (Criteria) this;
        }

        public Criteria andEMailIsNull() {
            addCriterion("E_MAIL is null");
            return (Criteria) this;
        }

        public Criteria andEMailIsNotNull() {
            addCriterion("E_MAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEMailEqualTo(String value) {
            addCriterion("E_MAIL =", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailNotEqualTo(String value) {
            addCriterion("E_MAIL <>", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailGreaterThan(String value) {
            addCriterion("E_MAIL >", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailGreaterThanOrEqualTo(String value) {
            addCriterion("E_MAIL >=", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailLessThan(String value) {
            addCriterion("E_MAIL <", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailLessThanOrEqualTo(String value) {
            addCriterion("E_MAIL <=", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailLike(String value) {
            addCriterion("E_MAIL like", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailNotLike(String value) {
            addCriterion("E_MAIL not like", value, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailIn(List<String> values) {
            addCriterion("E_MAIL in", values, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailNotIn(List<String> values) {
            addCriterion("E_MAIL not in", values, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailBetween(String value1, String value2) {
            addCriterion("E_MAIL between", value1, value2, "eMail");
            return (Criteria) this;
        }

        public Criteria andEMailNotBetween(String value1, String value2) {
            addCriterion("E_MAIL not between", value1, value2, "eMail");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneIsNull() {
            addCriterion("MOBILE_PHONE is null");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneIsNotNull() {
            addCriterion("MOBILE_PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneEqualTo(String value) {
            addCriterion("MOBILE_PHONE =", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotEqualTo(String value) {
            addCriterion("MOBILE_PHONE <>", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneGreaterThan(String value) {
            addCriterion("MOBILE_PHONE >", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("MOBILE_PHONE >=", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneLessThan(String value) {
            addCriterion("MOBILE_PHONE <", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneLessThanOrEqualTo(String value) {
            addCriterion("MOBILE_PHONE <=", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneLike(String value) {
            addCriterion("MOBILE_PHONE like", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotLike(String value) {
            addCriterion("MOBILE_PHONE not like", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneIn(List<String> values) {
            addCriterion("MOBILE_PHONE in", values, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotIn(List<String> values) {
            addCriterion("MOBILE_PHONE not in", values, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneBetween(String value1, String value2) {
            addCriterion("MOBILE_PHONE between", value1, value2, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotBetween(String value1, String value2) {
            addCriterion("MOBILE_PHONE not between", value1, value2, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andTelPhoneIsNull() {
            addCriterion("TEL_PHONE is null");
            return (Criteria) this;
        }

        public Criteria andTelPhoneIsNotNull() {
            addCriterion("TEL_PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andTelPhoneEqualTo(String value) {
            addCriterion("TEL_PHONE =", value, "telPhone");
            return (Criteria) this;
        }

        public Criteria andTelPhoneNotEqualTo(String value) {
            addCriterion("TEL_PHONE <>", value, "telPhone");
            return (Criteria) this;
        }

        public Criteria andTelPhoneGreaterThan(String value) {
            addCriterion("TEL_PHONE >", value, "telPhone");
            return (Criteria) this;
        }

        public Criteria andTelPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("TEL_PHONE >=", value, "telPhone");
            return (Criteria) this;
        }

        public Criteria andTelPhoneLessThan(String value) {
            addCriterion("TEL_PHONE <", value, "telPhone");
            return (Criteria) this;
        }

        public Criteria andTelPhoneLessThanOrEqualTo(String value) {
            addCriterion("TEL_PHONE <=", value, "telPhone");
            return (Criteria) this;
        }

        public Criteria andTelPhoneLike(String value) {
            addCriterion("TEL_PHONE like", value, "telPhone");
            return (Criteria) this;
        }

        public Criteria andTelPhoneNotLike(String value) {
            addCriterion("TEL_PHONE not like", value, "telPhone");
            return (Criteria) this;
        }

        public Criteria andTelPhoneIn(List<String> values) {
            addCriterion("TEL_PHONE in", values, "telPhone");
            return (Criteria) this;
        }

        public Criteria andTelPhoneNotIn(List<String> values) {
            addCriterion("TEL_PHONE not in", values, "telPhone");
            return (Criteria) this;
        }

        public Criteria andTelPhoneBetween(String value1, String value2) {
            addCriterion("TEL_PHONE between", value1, value2, "telPhone");
            return (Criteria) this;
        }

        public Criteria andTelPhoneNotBetween(String value1, String value2) {
            addCriterion("TEL_PHONE not between", value1, value2, "telPhone");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("CODE is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("CODE =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("CODE <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("CODE >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CODE >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("CODE <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("CODE <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("CODE like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("CODE not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("CODE in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("CODE not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("CODE between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("CODE not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("ADDRESS =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("ADDRESS <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("ADDRESS >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("ADDRESS <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("ADDRESS <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("ADDRESS like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("ADDRESS not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("ADDRESS in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("ADDRESS not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("ADDRESS between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("ADDRESS not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andPwdQuestionIsNull() {
            addCriterion("PWD_QUESTION is null");
            return (Criteria) this;
        }

        public Criteria andPwdQuestionIsNotNull() {
            addCriterion("PWD_QUESTION is not null");
            return (Criteria) this;
        }

        public Criteria andPwdQuestionEqualTo(String value) {
            addCriterion("PWD_QUESTION =", value, "pwdQuestion");
            return (Criteria) this;
        }

        public Criteria andPwdQuestionNotEqualTo(String value) {
            addCriterion("PWD_QUESTION <>", value, "pwdQuestion");
            return (Criteria) this;
        }

        public Criteria andPwdQuestionGreaterThan(String value) {
            addCriterion("PWD_QUESTION >", value, "pwdQuestion");
            return (Criteria) this;
        }

        public Criteria andPwdQuestionGreaterThanOrEqualTo(String value) {
            addCriterion("PWD_QUESTION >=", value, "pwdQuestion");
            return (Criteria) this;
        }

        public Criteria andPwdQuestionLessThan(String value) {
            addCriterion("PWD_QUESTION <", value, "pwdQuestion");
            return (Criteria) this;
        }

        public Criteria andPwdQuestionLessThanOrEqualTo(String value) {
            addCriterion("PWD_QUESTION <=", value, "pwdQuestion");
            return (Criteria) this;
        }

        public Criteria andPwdQuestionLike(String value) {
            addCriterion("PWD_QUESTION like", value, "pwdQuestion");
            return (Criteria) this;
        }

        public Criteria andPwdQuestionNotLike(String value) {
            addCriterion("PWD_QUESTION not like", value, "pwdQuestion");
            return (Criteria) this;
        }

        public Criteria andPwdQuestionIn(List<String> values) {
            addCriterion("PWD_QUESTION in", values, "pwdQuestion");
            return (Criteria) this;
        }

        public Criteria andPwdQuestionNotIn(List<String> values) {
            addCriterion("PWD_QUESTION not in", values, "pwdQuestion");
            return (Criteria) this;
        }

        public Criteria andPwdQuestionBetween(String value1, String value2) {
            addCriterion("PWD_QUESTION between", value1, value2, "pwdQuestion");
            return (Criteria) this;
        }

        public Criteria andPwdQuestionNotBetween(String value1, String value2) {
            addCriterion("PWD_QUESTION not between", value1, value2, "pwdQuestion");
            return (Criteria) this;
        }

        public Criteria andPwdAnswerIsNull() {
            addCriterion("PWD_ANSWER is null");
            return (Criteria) this;
        }

        public Criteria andPwdAnswerIsNotNull() {
            addCriterion("PWD_ANSWER is not null");
            return (Criteria) this;
        }

        public Criteria andPwdAnswerEqualTo(String value) {
            addCriterion("PWD_ANSWER =", value, "pwdAnswer");
            return (Criteria) this;
        }

        public Criteria andPwdAnswerNotEqualTo(String value) {
            addCriterion("PWD_ANSWER <>", value, "pwdAnswer");
            return (Criteria) this;
        }

        public Criteria andPwdAnswerGreaterThan(String value) {
            addCriterion("PWD_ANSWER >", value, "pwdAnswer");
            return (Criteria) this;
        }

        public Criteria andPwdAnswerGreaterThanOrEqualTo(String value) {
            addCriterion("PWD_ANSWER >=", value, "pwdAnswer");
            return (Criteria) this;
        }

        public Criteria andPwdAnswerLessThan(String value) {
            addCriterion("PWD_ANSWER <", value, "pwdAnswer");
            return (Criteria) this;
        }

        public Criteria andPwdAnswerLessThanOrEqualTo(String value) {
            addCriterion("PWD_ANSWER <=", value, "pwdAnswer");
            return (Criteria) this;
        }

        public Criteria andPwdAnswerLike(String value) {
            addCriterion("PWD_ANSWER like", value, "pwdAnswer");
            return (Criteria) this;
        }

        public Criteria andPwdAnswerNotLike(String value) {
            addCriterion("PWD_ANSWER not like", value, "pwdAnswer");
            return (Criteria) this;
        }

        public Criteria andPwdAnswerIn(List<String> values) {
            addCriterion("PWD_ANSWER in", values, "pwdAnswer");
            return (Criteria) this;
        }

        public Criteria andPwdAnswerNotIn(List<String> values) {
            addCriterion("PWD_ANSWER not in", values, "pwdAnswer");
            return (Criteria) this;
        }

        public Criteria andPwdAnswerBetween(String value1, String value2) {
            addCriterion("PWD_ANSWER between", value1, value2, "pwdAnswer");
            return (Criteria) this;
        }

        public Criteria andPwdAnswerNotBetween(String value1, String value2) {
            addCriterion("PWD_ANSWER not between", value1, value2, "pwdAnswer");
            return (Criteria) this;
        }

        public Criteria andPaperTypeIsNull() {
            addCriterion("PAPER_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andPaperTypeIsNotNull() {
            addCriterion("PAPER_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andPaperTypeEqualTo(String value) {
            addCriterion("PAPER_TYPE =", value, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeNotEqualTo(String value) {
            addCriterion("PAPER_TYPE <>", value, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeGreaterThan(String value) {
            addCriterion("PAPER_TYPE >", value, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeGreaterThanOrEqualTo(String value) {
            addCriterion("PAPER_TYPE >=", value, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeLessThan(String value) {
            addCriterion("PAPER_TYPE <", value, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeLessThanOrEqualTo(String value) {
            addCriterion("PAPER_TYPE <=", value, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeLike(String value) {
            addCriterion("PAPER_TYPE like", value, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeNotLike(String value) {
            addCriterion("PAPER_TYPE not like", value, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeIn(List<String> values) {
            addCriterion("PAPER_TYPE in", values, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeNotIn(List<String> values) {
            addCriterion("PAPER_TYPE not in", values, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeBetween(String value1, String value2) {
            addCriterion("PAPER_TYPE between", value1, value2, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeNotBetween(String value1, String value2) {
            addCriterion("PAPER_TYPE not between", value1, value2, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperCodeIsNull() {
            addCriterion("PAPER_CODE is null");
            return (Criteria) this;
        }

        public Criteria andPaperCodeIsNotNull() {
            addCriterion("PAPER_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andPaperCodeEqualTo(String value) {
            addCriterion("PAPER_CODE =", value, "paperCode");
            return (Criteria) this;
        }

        public Criteria andPaperCodeNotEqualTo(String value) {
            addCriterion("PAPER_CODE <>", value, "paperCode");
            return (Criteria) this;
        }

        public Criteria andPaperCodeGreaterThan(String value) {
            addCriterion("PAPER_CODE >", value, "paperCode");
            return (Criteria) this;
        }

        public Criteria andPaperCodeGreaterThanOrEqualTo(String value) {
            addCriterion("PAPER_CODE >=", value, "paperCode");
            return (Criteria) this;
        }

        public Criteria andPaperCodeLessThan(String value) {
            addCriterion("PAPER_CODE <", value, "paperCode");
            return (Criteria) this;
        }

        public Criteria andPaperCodeLessThanOrEqualTo(String value) {
            addCriterion("PAPER_CODE <=", value, "paperCode");
            return (Criteria) this;
        }

        public Criteria andPaperCodeLike(String value) {
            addCriterion("PAPER_CODE like", value, "paperCode");
            return (Criteria) this;
        }

        public Criteria andPaperCodeNotLike(String value) {
            addCriterion("PAPER_CODE not like", value, "paperCode");
            return (Criteria) this;
        }

        public Criteria andPaperCodeIn(List<String> values) {
            addCriterion("PAPER_CODE in", values, "paperCode");
            return (Criteria) this;
        }

        public Criteria andPaperCodeNotIn(List<String> values) {
            addCriterion("PAPER_CODE not in", values, "paperCode");
            return (Criteria) this;
        }

        public Criteria andPaperCodeBetween(String value1, String value2) {
            addCriterion("PAPER_CODE between", value1, value2, "paperCode");
            return (Criteria) this;
        }

        public Criteria andPaperCodeNotBetween(String value1, String value2) {
            addCriterion("PAPER_CODE not between", value1, value2, "paperCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeIsNull() {
            addCriterion("UNIT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andUnitCodeIsNotNull() {
            addCriterion("UNIT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andUnitCodeEqualTo(String value) {
            addCriterion("UNIT_CODE =", value, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeNotEqualTo(String value) {
            addCriterion("UNIT_CODE <>", value, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeGreaterThan(String value) {
            addCriterion("UNIT_CODE >", value, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeGreaterThanOrEqualTo(String value) {
            addCriterion("UNIT_CODE >=", value, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeLessThan(String value) {
            addCriterion("UNIT_CODE <", value, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeLessThanOrEqualTo(String value) {
            addCriterion("UNIT_CODE <=", value, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeLike(String value) {
            addCriterion("UNIT_CODE like", value, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeNotLike(String value) {
            addCriterion("UNIT_CODE not like", value, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeIn(List<String> values) {
            addCriterion("UNIT_CODE in", values, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeNotIn(List<String> values) {
            addCriterion("UNIT_CODE not in", values, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeBetween(String value1, String value2) {
            addCriterion("UNIT_CODE between", value1, value2, "unitCode");
            return (Criteria) this;
        }

        public Criteria andUnitCodeNotBetween(String value1, String value2) {
            addCriterion("UNIT_CODE not between", value1, value2, "unitCode");
            return (Criteria) this;
        }

        public Criteria andCheckStateIsNull() {
            addCriterion("CHECK_STATE is null");
            return (Criteria) this;
        }

        public Criteria andCheckStateIsNotNull() {
            addCriterion("CHECK_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andCheckStateEqualTo(String value) {
            addCriterion("CHECK_STATE =", value, "checkState");
            return (Criteria) this;
        }

        public Criteria andCheckStateNotEqualTo(String value) {
            addCriterion("CHECK_STATE <>", value, "checkState");
            return (Criteria) this;
        }

        public Criteria andCheckStateGreaterThan(String value) {
            addCriterion("CHECK_STATE >", value, "checkState");
            return (Criteria) this;
        }

        public Criteria andCheckStateGreaterThanOrEqualTo(String value) {
            addCriterion("CHECK_STATE >=", value, "checkState");
            return (Criteria) this;
        }

        public Criteria andCheckStateLessThan(String value) {
            addCriterion("CHECK_STATE <", value, "checkState");
            return (Criteria) this;
        }

        public Criteria andCheckStateLessThanOrEqualTo(String value) {
            addCriterion("CHECK_STATE <=", value, "checkState");
            return (Criteria) this;
        }

        public Criteria andCheckStateLike(String value) {
            addCriterion("CHECK_STATE like", value, "checkState");
            return (Criteria) this;
        }

        public Criteria andCheckStateNotLike(String value) {
            addCriterion("CHECK_STATE not like", value, "checkState");
            return (Criteria) this;
        }

        public Criteria andCheckStateIn(List<String> values) {
            addCriterion("CHECK_STATE in", values, "checkState");
            return (Criteria) this;
        }

        public Criteria andCheckStateNotIn(List<String> values) {
            addCriterion("CHECK_STATE not in", values, "checkState");
            return (Criteria) this;
        }

        public Criteria andCheckStateBetween(String value1, String value2) {
            addCriterion("CHECK_STATE between", value1, value2, "checkState");
            return (Criteria) this;
        }

        public Criteria andCheckStateNotBetween(String value1, String value2) {
            addCriterion("CHECK_STATE not between", value1, value2, "checkState");
            return (Criteria) this;
        }

        public Criteria andCaSnIsNull() {
            addCriterion("CA_SN is null");
            return (Criteria) this;
        }

        public Criteria andCaSnIsNotNull() {
            addCriterion("CA_SN is not null");
            return (Criteria) this;
        }

        public Criteria andCaSnEqualTo(String value) {
            addCriterion("CA_SN =", value, "caSn");
            return (Criteria) this;
        }

        public Criteria andCaSnNotEqualTo(String value) {
            addCriterion("CA_SN <>", value, "caSn");
            return (Criteria) this;
        }

        public Criteria andCaSnGreaterThan(String value) {
            addCriterion("CA_SN >", value, "caSn");
            return (Criteria) this;
        }

        public Criteria andCaSnGreaterThanOrEqualTo(String value) {
            addCriterion("CA_SN >=", value, "caSn");
            return (Criteria) this;
        }

        public Criteria andCaSnLessThan(String value) {
            addCriterion("CA_SN <", value, "caSn");
            return (Criteria) this;
        }

        public Criteria andCaSnLessThanOrEqualTo(String value) {
            addCriterion("CA_SN <=", value, "caSn");
            return (Criteria) this;
        }

        public Criteria andCaSnLike(String value) {
            addCriterion("CA_SN like", value, "caSn");
            return (Criteria) this;
        }

        public Criteria andCaSnNotLike(String value) {
            addCriterion("CA_SN not like", value, "caSn");
            return (Criteria) this;
        }

        public Criteria andCaSnIn(List<String> values) {
            addCriterion("CA_SN in", values, "caSn");
            return (Criteria) this;
        }

        public Criteria andCaSnNotIn(List<String> values) {
            addCriterion("CA_SN not in", values, "caSn");
            return (Criteria) this;
        }

        public Criteria andCaSnBetween(String value1, String value2) {
            addCriterion("CA_SN between", value1, value2, "caSn");
            return (Criteria) this;
        }

        public Criteria andCaSnNotBetween(String value1, String value2) {
            addCriterion("CA_SN not between", value1, value2, "caSn");
            return (Criteria) this;
        }

        public Criteria andBarCodeIsNull() {
            addCriterion("BAR_CODE is null");
            return (Criteria) this;
        }

        public Criteria andBarCodeIsNotNull() {
            addCriterion("BAR_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andBarCodeEqualTo(String value) {
            addCriterion("BAR_CODE =", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeNotEqualTo(String value) {
            addCriterion("BAR_CODE <>", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeGreaterThan(String value) {
            addCriterion("BAR_CODE >", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeGreaterThanOrEqualTo(String value) {
            addCriterion("BAR_CODE >=", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeLessThan(String value) {
            addCriterion("BAR_CODE <", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeLessThanOrEqualTo(String value) {
            addCriterion("BAR_CODE <=", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeLike(String value) {
            addCriterion("BAR_CODE like", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeNotLike(String value) {
            addCriterion("BAR_CODE not like", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeIn(List<String> values) {
            addCriterion("BAR_CODE in", values, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeNotIn(List<String> values) {
            addCriterion("BAR_CODE not in", values, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeBetween(String value1, String value2) {
            addCriterion("BAR_CODE between", value1, value2, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeNotBetween(String value1, String value2) {
            addCriterion("BAR_CODE not between", value1, value2, "barCode");
            return (Criteria) this;
        }

        public Criteria andLockdateIsNull() {
            addCriterion("LOCKDATE is null");
            return (Criteria) this;
        }

        public Criteria andLockdateIsNotNull() {
            addCriterion("LOCKDATE is not null");
            return (Criteria) this;
        }

        public Criteria andLockdateEqualTo(Date value) {
            addCriterionForJDBCDate("LOCKDATE =", value, "lockdate");
            return (Criteria) this;
        }

        public Criteria andLockdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("LOCKDATE <>", value, "lockdate");
            return (Criteria) this;
        }

        public Criteria andLockdateGreaterThan(Date value) {
            addCriterionForJDBCDate("LOCKDATE >", value, "lockdate");
            return (Criteria) this;
        }

        public Criteria andLockdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("LOCKDATE >=", value, "lockdate");
            return (Criteria) this;
        }

        public Criteria andLockdateLessThan(Date value) {
            addCriterionForJDBCDate("LOCKDATE <", value, "lockdate");
            return (Criteria) this;
        }

        public Criteria andLockdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("LOCKDATE <=", value, "lockdate");
            return (Criteria) this;
        }

        public Criteria andLockdateIn(List<Date> values) {
            addCriterionForJDBCDate("LOCKDATE in", values, "lockdate");
            return (Criteria) this;
        }

        public Criteria andLockdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("LOCKDATE not in", values, "lockdate");
            return (Criteria) this;
        }

        public Criteria andLockdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("LOCKDATE between", value1, value2, "lockdate");
            return (Criteria) this;
        }

        public Criteria andLockdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("LOCKDATE not between", value1, value2, "lockdate");
            return (Criteria) this;
        }

        public Criteria andUType2IsNull() {
            addCriterion("U_TYPE2 is null");
            return (Criteria) this;
        }

        public Criteria andUType2IsNotNull() {
            addCriterion("U_TYPE2 is not null");
            return (Criteria) this;
        }

        public Criteria andUType2EqualTo(String value) {
            addCriterion("U_TYPE2 =", value, "uType2");
            return (Criteria) this;
        }

        public Criteria andUType2NotEqualTo(String value) {
            addCriterion("U_TYPE2 <>", value, "uType2");
            return (Criteria) this;
        }

        public Criteria andUType2GreaterThan(String value) {
            addCriterion("U_TYPE2 >", value, "uType2");
            return (Criteria) this;
        }

        public Criteria andUType2GreaterThanOrEqualTo(String value) {
            addCriterion("U_TYPE2 >=", value, "uType2");
            return (Criteria) this;
        }

        public Criteria andUType2LessThan(String value) {
            addCriterion("U_TYPE2 <", value, "uType2");
            return (Criteria) this;
        }

        public Criteria andUType2LessThanOrEqualTo(String value) {
            addCriterion("U_TYPE2 <=", value, "uType2");
            return (Criteria) this;
        }

        public Criteria andUType2Like(String value) {
            addCriterion("U_TYPE2 like", value, "uType2");
            return (Criteria) this;
        }

        public Criteria andUType2NotLike(String value) {
            addCriterion("U_TYPE2 not like", value, "uType2");
            return (Criteria) this;
        }

        public Criteria andUType2In(List<String> values) {
            addCriterion("U_TYPE2 in", values, "uType2");
            return (Criteria) this;
        }

        public Criteria andUType2NotIn(List<String> values) {
            addCriterion("U_TYPE2 not in", values, "uType2");
            return (Criteria) this;
        }

        public Criteria andUType2Between(String value1, String value2) {
            addCriterion("U_TYPE2 between", value1, value2, "uType2");
            return (Criteria) this;
        }

        public Criteria andUType2NotBetween(String value1, String value2) {
            addCriterion("U_TYPE2 not between", value1, value2, "uType2");
            return (Criteria) this;
        }

        public Criteria andIsNewEstablishIsNull() {
            addCriterion("IS_NEW_ESTABLISH is null");
            return (Criteria) this;
        }

        public Criteria andIsNewEstablishIsNotNull() {
            addCriterion("IS_NEW_ESTABLISH is not null");
            return (Criteria) this;
        }

        public Criteria andIsNewEstablishEqualTo(String value) {
            addCriterion("IS_NEW_ESTABLISH =", value, "isNewEstablish");
            return (Criteria) this;
        }

        public Criteria andIsNewEstablishNotEqualTo(String value) {
            addCriterion("IS_NEW_ESTABLISH <>", value, "isNewEstablish");
            return (Criteria) this;
        }

        public Criteria andIsNewEstablishGreaterThan(String value) {
            addCriterion("IS_NEW_ESTABLISH >", value, "isNewEstablish");
            return (Criteria) this;
        }

        public Criteria andIsNewEstablishGreaterThanOrEqualTo(String value) {
            addCriterion("IS_NEW_ESTABLISH >=", value, "isNewEstablish");
            return (Criteria) this;
        }

        public Criteria andIsNewEstablishLessThan(String value) {
            addCriterion("IS_NEW_ESTABLISH <", value, "isNewEstablish");
            return (Criteria) this;
        }

        public Criteria andIsNewEstablishLessThanOrEqualTo(String value) {
            addCriterion("IS_NEW_ESTABLISH <=", value, "isNewEstablish");
            return (Criteria) this;
        }

        public Criteria andIsNewEstablishLike(String value) {
            addCriterion("IS_NEW_ESTABLISH like", value, "isNewEstablish");
            return (Criteria) this;
        }

        public Criteria andIsNewEstablishNotLike(String value) {
            addCriterion("IS_NEW_ESTABLISH not like", value, "isNewEstablish");
            return (Criteria) this;
        }

        public Criteria andIsNewEstablishIn(List<String> values) {
            addCriterion("IS_NEW_ESTABLISH in", values, "isNewEstablish");
            return (Criteria) this;
        }

        public Criteria andIsNewEstablishNotIn(List<String> values) {
            addCriterion("IS_NEW_ESTABLISH not in", values, "isNewEstablish");
            return (Criteria) this;
        }

        public Criteria andIsNewEstablishBetween(String value1, String value2) {
            addCriterion("IS_NEW_ESTABLISH between", value1, value2, "isNewEstablish");
            return (Criteria) this;
        }

        public Criteria andIsNewEstablishNotBetween(String value1, String value2) {
            addCriterion("IS_NEW_ESTABLISH not between", value1, value2, "isNewEstablish");
            return (Criteria) this;
        }

        public Criteria andUserRegTimeIsNull() {
            addCriterion("USER_REG_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUserRegTimeIsNotNull() {
            addCriterion("USER_REG_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUserRegTimeEqualTo(Date value) {
            addCriterionForJDBCDate("USER_REG_TIME =", value, "userRegTime");
            return (Criteria) this;
        }

        public Criteria andUserRegTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("USER_REG_TIME <>", value, "userRegTime");
            return (Criteria) this;
        }

        public Criteria andUserRegTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("USER_REG_TIME >", value, "userRegTime");
            return (Criteria) this;
        }

        public Criteria andUserRegTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("USER_REG_TIME >=", value, "userRegTime");
            return (Criteria) this;
        }

        public Criteria andUserRegTimeLessThan(Date value) {
            addCriterionForJDBCDate("USER_REG_TIME <", value, "userRegTime");
            return (Criteria) this;
        }

        public Criteria andUserRegTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("USER_REG_TIME <=", value, "userRegTime");
            return (Criteria) this;
        }

        public Criteria andUserRegTimeIn(List<Date> values) {
            addCriterionForJDBCDate("USER_REG_TIME in", values, "userRegTime");
            return (Criteria) this;
        }

        public Criteria andUserRegTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("USER_REG_TIME not in", values, "userRegTime");
            return (Criteria) this;
        }

        public Criteria andUserRegTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("USER_REG_TIME between", value1, value2, "userRegTime");
            return (Criteria) this;
        }

        public Criteria andUserRegTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("USER_REG_TIME not between", value1, value2, "userRegTime");
            return (Criteria) this;
        }

        public Criteria andHandlerNameIsNull() {
            addCriterion("HANDLER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andHandlerNameIsNotNull() {
            addCriterion("HANDLER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andHandlerNameEqualTo(String value) {
            addCriterion("HANDLER_NAME =", value, "handlerName");
            return (Criteria) this;
        }

        public Criteria andHandlerNameNotEqualTo(String value) {
            addCriterion("HANDLER_NAME <>", value, "handlerName");
            return (Criteria) this;
        }

        public Criteria andHandlerNameGreaterThan(String value) {
            addCriterion("HANDLER_NAME >", value, "handlerName");
            return (Criteria) this;
        }

        public Criteria andHandlerNameGreaterThanOrEqualTo(String value) {
            addCriterion("HANDLER_NAME >=", value, "handlerName");
            return (Criteria) this;
        }

        public Criteria andHandlerNameLessThan(String value) {
            addCriterion("HANDLER_NAME <", value, "handlerName");
            return (Criteria) this;
        }

        public Criteria andHandlerNameLessThanOrEqualTo(String value) {
            addCriterion("HANDLER_NAME <=", value, "handlerName");
            return (Criteria) this;
        }

        public Criteria andHandlerNameLike(String value) {
            addCriterion("HANDLER_NAME like", value, "handlerName");
            return (Criteria) this;
        }

        public Criteria andHandlerNameNotLike(String value) {
            addCriterion("HANDLER_NAME not like", value, "handlerName");
            return (Criteria) this;
        }

        public Criteria andHandlerNameIn(List<String> values) {
            addCriterion("HANDLER_NAME in", values, "handlerName");
            return (Criteria) this;
        }

        public Criteria andHandlerNameNotIn(List<String> values) {
            addCriterion("HANDLER_NAME not in", values, "handlerName");
            return (Criteria) this;
        }

        public Criteria andHandlerNameBetween(String value1, String value2) {
            addCriterion("HANDLER_NAME between", value1, value2, "handlerName");
            return (Criteria) this;
        }

        public Criteria andHandlerNameNotBetween(String value1, String value2) {
            addCriterion("HANDLER_NAME not between", value1, value2, "handlerName");
            return (Criteria) this;
        }

        public Criteria andHandlerIdIsNull() {
            addCriterion("HANDLER_ID is null");
            return (Criteria) this;
        }

        public Criteria andHandlerIdIsNotNull() {
            addCriterion("HANDLER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andHandlerIdEqualTo(String value) {
            addCriterion("HANDLER_ID =", value, "handlerId");
            return (Criteria) this;
        }

        public Criteria andHandlerIdNotEqualTo(String value) {
            addCriterion("HANDLER_ID <>", value, "handlerId");
            return (Criteria) this;
        }

        public Criteria andHandlerIdGreaterThan(String value) {
            addCriterion("HANDLER_ID >", value, "handlerId");
            return (Criteria) this;
        }

        public Criteria andHandlerIdGreaterThanOrEqualTo(String value) {
            addCriterion("HANDLER_ID >=", value, "handlerId");
            return (Criteria) this;
        }

        public Criteria andHandlerIdLessThan(String value) {
            addCriterion("HANDLER_ID <", value, "handlerId");
            return (Criteria) this;
        }

        public Criteria andHandlerIdLessThanOrEqualTo(String value) {
            addCriterion("HANDLER_ID <=", value, "handlerId");
            return (Criteria) this;
        }

        public Criteria andHandlerIdLike(String value) {
            addCriterion("HANDLER_ID like", value, "handlerId");
            return (Criteria) this;
        }

        public Criteria andHandlerIdNotLike(String value) {
            addCriterion("HANDLER_ID not like", value, "handlerId");
            return (Criteria) this;
        }

        public Criteria andHandlerIdIn(List<String> values) {
            addCriterion("HANDLER_ID in", values, "handlerId");
            return (Criteria) this;
        }

        public Criteria andHandlerIdNotIn(List<String> values) {
            addCriterion("HANDLER_ID not in", values, "handlerId");
            return (Criteria) this;
        }

        public Criteria andHandlerIdBetween(String value1, String value2) {
            addCriterion("HANDLER_ID between", value1, value2, "handlerId");
            return (Criteria) this;
        }

        public Criteria andHandlerIdNotBetween(String value1, String value2) {
            addCriterion("HANDLER_ID not between", value1, value2, "handlerId");
            return (Criteria) this;
        }

        public Criteria andEUidIsNull() {
            addCriterion("E_UID is null");
            return (Criteria) this;
        }

        public Criteria andEUidIsNotNull() {
            addCriterion("E_UID is not null");
            return (Criteria) this;
        }

        public Criteria andEUidEqualTo(String value) {
            addCriterion("E_UID =", value, "eUid");
            return (Criteria) this;
        }

        public Criteria andEUidNotEqualTo(String value) {
            addCriterion("E_UID <>", value, "eUid");
            return (Criteria) this;
        }

        public Criteria andEUidGreaterThan(String value) {
            addCriterion("E_UID >", value, "eUid");
            return (Criteria) this;
        }

        public Criteria andEUidGreaterThanOrEqualTo(String value) {
            addCriterion("E_UID >=", value, "eUid");
            return (Criteria) this;
        }

        public Criteria andEUidLessThan(String value) {
            addCriterion("E_UID <", value, "eUid");
            return (Criteria) this;
        }

        public Criteria andEUidLessThanOrEqualTo(String value) {
            addCriterion("E_UID <=", value, "eUid");
            return (Criteria) this;
        }

        public Criteria andEUidLike(String value) {
            addCriterion("E_UID like", value, "eUid");
            return (Criteria) this;
        }

        public Criteria andEUidNotLike(String value) {
            addCriterion("E_UID not like", value, "eUid");
            return (Criteria) this;
        }

        public Criteria andEUidIn(List<String> values) {
            addCriterion("E_UID in", values, "eUid");
            return (Criteria) this;
        }

        public Criteria andEUidNotIn(List<String> values) {
            addCriterion("E_UID not in", values, "eUid");
            return (Criteria) this;
        }

        public Criteria andEUidBetween(String value1, String value2) {
            addCriterion("E_UID between", value1, value2, "eUid");
            return (Criteria) this;
        }

        public Criteria andEUidNotBetween(String value1, String value2) {
            addCriterion("E_UID not between", value1, value2, "eUid");
            return (Criteria) this;
        }

        public Criteria andExchangeStatusIsNull() {
            addCriterion("EXCHANGE_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andExchangeStatusIsNotNull() {
            addCriterion("EXCHANGE_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andExchangeStatusEqualTo(Short value) {
            addCriterion("EXCHANGE_STATUS =", value, "exchangeStatus");
            return (Criteria) this;
        }

        public Criteria andExchangeStatusNotEqualTo(Short value) {
            addCriterion("EXCHANGE_STATUS <>", value, "exchangeStatus");
            return (Criteria) this;
        }

        public Criteria andExchangeStatusGreaterThan(Short value) {
            addCriterion("EXCHANGE_STATUS >", value, "exchangeStatus");
            return (Criteria) this;
        }

        public Criteria andExchangeStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("EXCHANGE_STATUS >=", value, "exchangeStatus");
            return (Criteria) this;
        }

        public Criteria andExchangeStatusLessThan(Short value) {
            addCriterion("EXCHANGE_STATUS <", value, "exchangeStatus");
            return (Criteria) this;
        }

        public Criteria andExchangeStatusLessThanOrEqualTo(Short value) {
            addCriterion("EXCHANGE_STATUS <=", value, "exchangeStatus");
            return (Criteria) this;
        }

        public Criteria andExchangeStatusIn(List<Short> values) {
            addCriterion("EXCHANGE_STATUS in", values, "exchangeStatus");
            return (Criteria) this;
        }

        public Criteria andExchangeStatusNotIn(List<Short> values) {
            addCriterion("EXCHANGE_STATUS not in", values, "exchangeStatus");
            return (Criteria) this;
        }

        public Criteria andExchangeStatusBetween(Short value1, Short value2) {
            addCriterion("EXCHANGE_STATUS between", value1, value2, "exchangeStatus");
            return (Criteria) this;
        }

        public Criteria andExchangeStatusNotBetween(Short value1, Short value2) {
            addCriterion("EXCHANGE_STATUS not between", value1, value2, "exchangeStatus");
            return (Criteria) this;
        }

        public Criteria andPwdTypeIsNull() {
            addCriterion("PWD_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andPwdTypeIsNotNull() {
            addCriterion("PWD_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andPwdTypeEqualTo(Short value) {
            addCriterion("PWD_TYPE =", value, "pwdType");
            return (Criteria) this;
        }

        public Criteria andPwdTypeNotEqualTo(Short value) {
            addCriterion("PWD_TYPE <>", value, "pwdType");
            return (Criteria) this;
        }

        public Criteria andPwdTypeGreaterThan(Short value) {
            addCriterion("PWD_TYPE >", value, "pwdType");
            return (Criteria) this;
        }

        public Criteria andPwdTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("PWD_TYPE >=", value, "pwdType");
            return (Criteria) this;
        }

        public Criteria andPwdTypeLessThan(Short value) {
            addCriterion("PWD_TYPE <", value, "pwdType");
            return (Criteria) this;
        }

        public Criteria andPwdTypeLessThanOrEqualTo(Short value) {
            addCriterion("PWD_TYPE <=", value, "pwdType");
            return (Criteria) this;
        }

        public Criteria andPwdTypeIn(List<Short> values) {
            addCriterion("PWD_TYPE in", values, "pwdType");
            return (Criteria) this;
        }

        public Criteria andPwdTypeNotIn(List<Short> values) {
            addCriterion("PWD_TYPE not in", values, "pwdType");
            return (Criteria) this;
        }

        public Criteria andPwdTypeBetween(Short value1, Short value2) {
            addCriterion("PWD_TYPE between", value1, value2, "pwdType");
            return (Criteria) this;
        }

        public Criteria andPwdTypeNotBetween(Short value1, Short value2) {
            addCriterion("PWD_TYPE not between", value1, value2, "pwdType");
            return (Criteria) this;
        }

        public Criteria andIpNumberIsNull() {
            addCriterion("IP_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andIpNumberIsNotNull() {
            addCriterion("IP_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andIpNumberEqualTo(String value) {
            addCriterion("IP_NUMBER =", value, "ipNumber");
            return (Criteria) this;
        }

        public Criteria andIpNumberNotEqualTo(String value) {
            addCriterion("IP_NUMBER <>", value, "ipNumber");
            return (Criteria) this;
        }

        public Criteria andIpNumberGreaterThan(String value) {
            addCriterion("IP_NUMBER >", value, "ipNumber");
            return (Criteria) this;
        }

        public Criteria andIpNumberGreaterThanOrEqualTo(String value) {
            addCriterion("IP_NUMBER >=", value, "ipNumber");
            return (Criteria) this;
        }

        public Criteria andIpNumberLessThan(String value) {
            addCriterion("IP_NUMBER <", value, "ipNumber");
            return (Criteria) this;
        }

        public Criteria andIpNumberLessThanOrEqualTo(String value) {
            addCriterion("IP_NUMBER <=", value, "ipNumber");
            return (Criteria) this;
        }

        public Criteria andIpNumberLike(String value) {
            addCriterion("IP_NUMBER like", value, "ipNumber");
            return (Criteria) this;
        }

        public Criteria andIpNumberNotLike(String value) {
            addCriterion("IP_NUMBER not like", value, "ipNumber");
            return (Criteria) this;
        }

        public Criteria andIpNumberIn(List<String> values) {
            addCriterion("IP_NUMBER in", values, "ipNumber");
            return (Criteria) this;
        }

        public Criteria andIpNumberNotIn(List<String> values) {
            addCriterion("IP_NUMBER not in", values, "ipNumber");
            return (Criteria) this;
        }

        public Criteria andIpNumberBetween(String value1, String value2) {
            addCriterion("IP_NUMBER between", value1, value2, "ipNumber");
            return (Criteria) this;
        }

        public Criteria andIpNumberNotBetween(String value1, String value2) {
            addCriterion("IP_NUMBER not between", value1, value2, "ipNumber");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("VERSION like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("VERSION not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andIsSupplyIsNull() {
            addCriterion("IS_SUPPLY is null");
            return (Criteria) this;
        }

        public Criteria andIsSupplyIsNotNull() {
            addCriterion("IS_SUPPLY is not null");
            return (Criteria) this;
        }

        public Criteria andIsSupplyEqualTo(Short value) {
            addCriterion("IS_SUPPLY =", value, "isSupply");
            return (Criteria) this;
        }

        public Criteria andIsSupplyNotEqualTo(Short value) {
            addCriterion("IS_SUPPLY <>", value, "isSupply");
            return (Criteria) this;
        }

        public Criteria andIsSupplyGreaterThan(Short value) {
            addCriterion("IS_SUPPLY >", value, "isSupply");
            return (Criteria) this;
        }

        public Criteria andIsSupplyGreaterThanOrEqualTo(Short value) {
            addCriterion("IS_SUPPLY >=", value, "isSupply");
            return (Criteria) this;
        }

        public Criteria andIsSupplyLessThan(Short value) {
            addCriterion("IS_SUPPLY <", value, "isSupply");
            return (Criteria) this;
        }

        public Criteria andIsSupplyLessThanOrEqualTo(Short value) {
            addCriterion("IS_SUPPLY <=", value, "isSupply");
            return (Criteria) this;
        }

        public Criteria andIsSupplyIn(List<Short> values) {
            addCriterion("IS_SUPPLY in", values, "isSupply");
            return (Criteria) this;
        }

        public Criteria andIsSupplyNotIn(List<Short> values) {
            addCriterion("IS_SUPPLY not in", values, "isSupply");
            return (Criteria) this;
        }

        public Criteria andIsSupplyBetween(Short value1, Short value2) {
            addCriterion("IS_SUPPLY between", value1, value2, "isSupply");
            return (Criteria) this;
        }

        public Criteria andIsSupplyNotBetween(Short value1, Short value2) {
            addCriterion("IS_SUPPLY not between", value1, value2, "isSupply");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}