package mapper;

import com.lwt.springboot.domain.OuternetUserBean;
import com.lwt.springboot.domain.OuternetUserBeanExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface OuternetUserBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    int countByExample(OuternetUserBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    int deleteByExample(OuternetUserBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    @Delete({
        "delete from OUTERNET_USER",
        "where U_ID = #{uId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String uId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    @Insert({
        "insert into OUTERNET_USER (U_ID, U_TYPE, ",
        "U_NAME, U_PWD, TYPE, ",
        "NAME, LICENSE, ORG_CODE, ",
        "CORPORATION, CORPORATION_ID, ",
        "E_MAIL, MOBILE_PHONE, ",
        "TEL_PHONE, CODE, ",
        "ADDRESS, PWD_QUESTION, ",
        "PWD_ANSWER, PAPER_TYPE, ",
        "PAPER_CODE, UNIT_CODE, ",
        "CHECK_STATE, CA_SN, ",
        "BAR_CODE, LOCKDATE, ",
        "U_TYPE2, IS_NEW_ESTABLISH, ",
        "USER_REG_TIME, HANDLER_NAME, ",
        "HANDLER_ID, E_UID, ",
        "EXCHANGE_STATUS, PWD_TYPE, ",
        "IP_NUMBER, VERSION, ",
        "IS_SUPPLY)",
        "values (#{uId,jdbcType=VARCHAR}, #{uType,jdbcType=VARCHAR}, ",
        "#{uName,jdbcType=VARCHAR}, #{uPwd,jdbcType=VARCHAR}, #{type,jdbcType=VARCHAR}, ",
        "#{name,jdbcType=VARCHAR}, #{license,jdbcType=VARCHAR}, #{orgCode,jdbcType=VARCHAR}, ",
        "#{corporation,jdbcType=VARCHAR}, #{corporationId,jdbcType=VARCHAR}, ",
        "#{eMail,jdbcType=VARCHAR}, #{mobilePhone,jdbcType=VARCHAR}, ",
        "#{telPhone,jdbcType=VARCHAR}, #{code,jdbcType=VARCHAR}, ",
        "#{address,jdbcType=VARCHAR}, #{pwdQuestion,jdbcType=VARCHAR}, ",
        "#{pwdAnswer,jdbcType=VARCHAR}, #{paperType,jdbcType=VARCHAR}, ",
        "#{paperCode,jdbcType=VARCHAR}, #{unitCode,jdbcType=VARCHAR}, ",
        "#{checkState,jdbcType=VARCHAR}, #{caSn,jdbcType=VARCHAR}, ",
        "#{barCode,jdbcType=VARCHAR}, #{lockdate,jdbcType=DATE}, ",
        "#{uType2,jdbcType=VARCHAR}, #{isNewEstablish,jdbcType=VARCHAR}, ",
        "#{userRegTime,jdbcType=DATE}, #{handlerName,jdbcType=VARCHAR}, ",
        "#{handlerId,jdbcType=VARCHAR}, #{eUid,jdbcType=VARCHAR}, ",
        "#{exchangeStatus,jdbcType=DECIMAL}, #{pwdType,jdbcType=DECIMAL}, ",
        "#{ipNumber,jdbcType=VARCHAR}, #{version,jdbcType=VARCHAR}, ",
        "#{isSupply,jdbcType=DECIMAL})"
    })
    int insert(OuternetUserBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    int insertSelective(OuternetUserBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    List<OuternetUserBean> selectByExample(OuternetUserBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "U_ID, U_TYPE, U_NAME, U_PWD, TYPE, NAME, LICENSE, ORG_CODE, CORPORATION, CORPORATION_ID, ",
        "E_MAIL, MOBILE_PHONE, TEL_PHONE, CODE, ADDRESS, PWD_QUESTION, PWD_ANSWER, PAPER_TYPE, ",
        "PAPER_CODE, UNIT_CODE, CHECK_STATE, CA_SN, BAR_CODE, LOCKDATE, U_TYPE2, IS_NEW_ESTABLISH, ",
        "USER_REG_TIME, HANDLER_NAME, HANDLER_ID, E_UID, EXCHANGE_STATUS, PWD_TYPE, IP_NUMBER, ",
        "VERSION, IS_SUPPLY",
        "from OUTERNET_USER",
        "where U_ID = #{uId,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    OuternetUserBean selectByPrimaryKey(String uId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OuternetUserBean record, @Param("example") OuternetUserBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OuternetUserBean record, @Param("example") OuternetUserBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OuternetUserBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_USER
     *
     * @mbggenerated
     */
    @Update({
        "update OUTERNET_USER",
        "set U_TYPE = #{uType,jdbcType=VARCHAR},",
          "U_NAME = #{uName,jdbcType=VARCHAR},",
          "U_PWD = #{uPwd,jdbcType=VARCHAR},",
          "TYPE = #{type,jdbcType=VARCHAR},",
          "NAME = #{name,jdbcType=VARCHAR},",
          "LICENSE = #{license,jdbcType=VARCHAR},",
          "ORG_CODE = #{orgCode,jdbcType=VARCHAR},",
          "CORPORATION = #{corporation,jdbcType=VARCHAR},",
          "CORPORATION_ID = #{corporationId,jdbcType=VARCHAR},",
          "E_MAIL = #{eMail,jdbcType=VARCHAR},",
          "MOBILE_PHONE = #{mobilePhone,jdbcType=VARCHAR},",
          "TEL_PHONE = #{telPhone,jdbcType=VARCHAR},",
          "CODE = #{code,jdbcType=VARCHAR},",
          "ADDRESS = #{address,jdbcType=VARCHAR},",
          "PWD_QUESTION = #{pwdQuestion,jdbcType=VARCHAR},",
          "PWD_ANSWER = #{pwdAnswer,jdbcType=VARCHAR},",
          "PAPER_TYPE = #{paperType,jdbcType=VARCHAR},",
          "PAPER_CODE = #{paperCode,jdbcType=VARCHAR},",
          "UNIT_CODE = #{unitCode,jdbcType=VARCHAR},",
          "CHECK_STATE = #{checkState,jdbcType=VARCHAR},",
          "CA_SN = #{caSn,jdbcType=VARCHAR},",
          "BAR_CODE = #{barCode,jdbcType=VARCHAR},",
          "LOCKDATE = #{lockdate,jdbcType=DATE},",
          "U_TYPE2 = #{uType2,jdbcType=VARCHAR},",
          "IS_NEW_ESTABLISH = #{isNewEstablish,jdbcType=VARCHAR},",
          "USER_REG_TIME = #{userRegTime,jdbcType=DATE},",
          "HANDLER_NAME = #{handlerName,jdbcType=VARCHAR},",
          "HANDLER_ID = #{handlerId,jdbcType=VARCHAR},",
          "E_UID = #{eUid,jdbcType=VARCHAR},",
          "EXCHANGE_STATUS = #{exchangeStatus,jdbcType=DECIMAL},",
          "PWD_TYPE = #{pwdType,jdbcType=DECIMAL},",
          "IP_NUMBER = #{ipNumber,jdbcType=VARCHAR},",
          "VERSION = #{version,jdbcType=VARCHAR},",
          "IS_SUPPLY = #{isSupply,jdbcType=DECIMAL}",
        "where U_ID = #{uId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(OuternetUserBean record);
}