package mapper;

import com.lwt.springboot.domain.outernetBundlingUserBean;
import com.lwt.springboot.domain.outernetBundlingUserBeanExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface outernetBundlingUserBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_BUNDLING_USER
     *
     * @mbggenerated
     */
    int countByExample(outernetBundlingUserBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_BUNDLING_USER
     *
     * @mbggenerated
     */
    int deleteByExample(outernetBundlingUserBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_BUNDLING_USER
     *
     * @mbggenerated
     */
    @Delete({
        "delete from OUTERNET_BUNDLING_USER",
        "where BUNDLING_ID = #{bundlingId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String bundlingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_BUNDLING_USER
     *
     * @mbggenerated
     */
    @Insert({
        "insert into OUTERNET_BUNDLING_USER (BUNDLING_ID, LOGIN_ID, ",
        "USER_CODE, CREATE_DATE, ",
        "IS_VALID, ISP_NAME, ",
        "ISP_CODE, LOCAL_USER, ",
        "BUNDLING_USERID_CODE, BUNDLING_IS_REAL, ",
        "BUNDLING_UPDATE_TIME)",
        "values (#{bundlingId,jdbcType=VARCHAR}, #{loginId,jdbcType=VARCHAR}, ",
        "#{userCode,jdbcType=VARCHAR}, #{createDate,jdbcType=DATE}, ",
        "#{isValid,jdbcType=DECIMAL}, #{ispName,jdbcType=VARCHAR}, ",
        "#{ispCode,jdbcType=VARCHAR}, #{localUser,jdbcType=VARCHAR}, ",
        "#{bundlingUseridCode,jdbcType=VARCHAR}, #{bundlingIsReal,jdbcType=VARCHAR}, ",
        "#{bundlingUpdateTime,jdbcType=VARCHAR})"
    })
    int insert(outernetBundlingUserBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_BUNDLING_USER
     *
     * @mbggenerated
     */
    int insertSelective(outernetBundlingUserBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_BUNDLING_USER
     *
     * @mbggenerated
     */
    List<outernetBundlingUserBean> selectByExample(outernetBundlingUserBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_BUNDLING_USER
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "BUNDLING_ID, LOGIN_ID, USER_CODE, CREATE_DATE, IS_VALID, ISP_NAME, ISP_CODE, ",
        "LOCAL_USER, BUNDLING_USERID_CODE, BUNDLING_IS_REAL, BUNDLING_UPDATE_TIME",
        "from OUTERNET_BUNDLING_USER",
        "where BUNDLING_ID = #{bundlingId,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    outernetBundlingUserBean selectByPrimaryKey(String bundlingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_BUNDLING_USER
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") outernetBundlingUserBean record, @Param("example") outernetBundlingUserBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_BUNDLING_USER
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") outernetBundlingUserBean record, @Param("example") outernetBundlingUserBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_BUNDLING_USER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(outernetBundlingUserBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTERNET_BUNDLING_USER
     *
     * @mbggenerated
     */
    @Update({
        "update OUTERNET_BUNDLING_USER",
        "set LOGIN_ID = #{loginId,jdbcType=VARCHAR},",
          "USER_CODE = #{userCode,jdbcType=VARCHAR},",
          "CREATE_DATE = #{createDate,jdbcType=DATE},",
          "IS_VALID = #{isValid,jdbcType=DECIMAL},",
          "ISP_NAME = #{ispName,jdbcType=VARCHAR},",
          "ISP_CODE = #{ispCode,jdbcType=VARCHAR},",
          "LOCAL_USER = #{localUser,jdbcType=VARCHAR},",
          "BUNDLING_USERID_CODE = #{bundlingUseridCode,jdbcType=VARCHAR},",
          "BUNDLING_IS_REAL = #{bundlingIsReal,jdbcType=VARCHAR},",
          "BUNDLING_UPDATE_TIME = #{bundlingUpdateTime,jdbcType=VARCHAR}",
        "where BUNDLING_ID = #{bundlingId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(outernetBundlingUserBean record);
}